import Head from "next/head";

import "./globals.css";
import { Nav } from "./components/Nav";
import { Footer } from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head></Head>
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
